name: glueviz

dependencies:
  - qtpy
  - pyqt=5
  - numpy
  - matplotlib
  - pandas
  - astropy
  - dill
  - h5py
  - scipy
  - scikit-image
  - ipython
  - ipykernel
  - qtconsole
  - traitlets
  - pygments
  - pyzmq
  - mock
  - pytest
  - python>=3
