name: CI Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  initial_checks:
    # Mandatory checks before CI tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov

      envs: |
        # Linux build
        - linux: py310-test-all
        - linux: py313-test
        - linux: py314-test-all

        # Test a few configurations on macOS
        - macos: py311-test-all
        - macos: py312-test
        - macos: py313-test-all

        # Test some configurations on Windows
        - windows: py310-test
        - windows: py312-test-all
        - windows: py314-test

        # Test against latest developer versions of some packages
        - linux: py311-test-dev-all
        - linux: py313-test-dev-all
        - linux: py314-test-dev

        - macos: py310-test-dev
        - macos: py314-test-dev-all

        - windows: py312-test-dev-all
        - windows: py313-test-dev

        # Documentation build
        - linux: py310-docs
          coverage: false
        - macos: py311-docs
          coverage: false

  allowed_failures:
    # Test on pre-release Python versions here as nightly wheels may sometimes fail to build
    if: false
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov

      envs: |
        - linux: py315-test-dev

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: 'test'
      test_command: pytest --pyargs glue
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
